// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Model;

namespace Model.Migrations
{
    [DbContext(typeof(LmsDbContext))]
    [Migration("20180922015900_CourseAdded")]
    partial class CourseAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Model.Course", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("AverageRating");

                    b.Property<DateTime>("Created");

                    b.Property<string>("CreatedBy");

                    b.Property<double>("DiscountPrice");

                    b.Property<int>("EnrolledCount");

                    b.Property<string>("ImgUrl");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsFree");

                    b.Property<string>("Language");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("ModifiedBy");

                    b.Property<string>("Name");

                    b.Property<double>("RegularPrice");

                    b.Property<int>("StudentLavel");

                    b.Property<string>("Topic");

                    b.Property<int>("TotalDurationHour");

                    b.Property<int>("TotalLectureCount");

                    b.Property<string>("TrainerName");

                    b.Property<int>("ViewCount");

                    b.HasKey("Id");

                    b.HasIndex("IsFree");

                    b.HasIndex("Name");

                    b.HasIndex("Topic");

                    b.ToTable("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
